### ISSUE TITLE
In make_examples_simple(text_to_process3) :   Examples must contain at most two distinct segments. Segments beyond the second will be ignored.

### ISSUE THREAD

**Issue by johnERgordon** [jonathanbratt/RBERT#41]
I would like to retrieve BERT word-embeddings for entire paragraphs with more than 2 sentences. However, in the example below I have added a third sentence to the first "paragraph"; but it gives the error in the title. 
Does this mean the the third sentence has not been processed and contributed to the overall word embedding?  
And how do I do in order to get a word-embedding representing all three (and more) sentences in the first list? 

text_to_process3 <- list(c("Impulse is equal to the change in momentum.",
                           "Changing momentum requires an impulse.", "A third sentence give a warning."),
                         c("An impulse is like a push.",
                           "Impulse is force times time."))
text_to_process3
BERT_feats <- extract_features(
  examples =  make_examples_simple(text_to_process3),
  ckpt_dir = BERT_PRETRAINED_DIR,
  layer_indexes = 1:12,
  batch_size = 2L
)

Thank you for an awesome package!

**Comment by jonthegeek** [comment]
In this particular case, I'd merge the two `c`'s into a single string each, like:
ext_to_process3 <- c("Impulse is equal to the change in momentum. Changing momentum requires an impulse. A third sentence give a warning.", "An impulse is like a push. Impulse is force times time.")

BERT is built to take single strings, or paired strings that you want to compare to one another. Your use case is more the "single string" style.

I plan to update extract_features soon to make the input a bit easier to understand, I'll definitely keep this in mind as a use case to at a minimum warn about (but hopefully we can deal with it at least somewhat automatically.

Thanks for using the package, it definitely helps us figure out what we need to do next!

**Comment by jonathanbratt** [comment]
I'm thinking we should make a vignette that's an "introduction to BERT", which includes all the general BERT background that is currently assumed (e.g. sequence/segment input structure, what the attention weights output and layer output mean, etc.). What do you think, @jonthegeek?

**Comment by johnERgordon** [comment]
Thanks for the answer @jonthegeek! It works, and all my predictions actually increases significantly!
However, do I understand it correctly that with this way only 512 token are read; so in the cases when the text input is longer, it is ignored? 
And in that case is it possible to make it read all the texts different times and then add the word-embeddings together in order to produce an embedding summarising all the text input?

@jonathanbratt I think that would be very helpful indeed (but I also want to say that you have really succeeded in creating a user-friendly package already; Im rather new to R and I managed to get started relatively easy!) 
Thanks!

**Comment by jonathanbratt** [comment]
@johnERgordon 
Regarding the 512-token limit: correct--this is a hard limit in BERT. If you need to process longer pieces of text, you'll have to find a way to break it up.

Also, keep in mind that each piece of punctuation counts as a token, and words not found in the vocabulary will require at least two tokens, so you might hit the limit sooner than you expect. For example, the sentence "Who doesn't like tacos?" becomes 10 tokens ("[CLS] who doesn ' t like ta ##cos ? [SEP]").

**Comment by jonathanbratt** [comment]
@johnERgordon To your second question: I'm not sure whether adding the outputs together from many different input texts would result in something useful. I guess it depends on your particular use case. Let us know if you find something that works for you. :)

**Comment by jonthegeek** [comment]
@johnERgordon see if the changes in the latest version address this issue for you!
