### ISSUE TITLE
extract_features by model name

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/RBERT#44]
As an RBERT user, I'd like to extract features from text without having to overthink the model backend. Allow the user to specify a "model" like in `download_BERT_checkpoint`, and then infer everything else from that.

Note that this will change the order of the arguments again (adding "model" as the second argument).

**Comment by jonthegeek** [comment]
Also update parameters in `tokenize_text` and `check_vocab`.

**Comment by jonathanbratt** [comment]
yeah, I like this idea.
