### ISSUE TITLE
Better use_one_hot_embeddings documentation in extract_features

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/RBERT#45]
The documentation for use_one_hot_embeddings says: "Logical; whether to use one-hot word embeddings or tf.embedding_lookup() for the word embeddings."

I can get most of that from the name of the parameter. What's the difference between those two options? 

Also update `.model_fn_builder_EF` to inherit this param from `extract_features` (or vice versa?), so it's documented the same in both places. Actually, `BertModel` also uses it, and it looks like its "home" is `embedding_lookup`. The documentation there is slightly different, but neither really helps me grok what the difference is/when I'd want it to be TRUE.

**Comment by jonathanbratt** [comment]
Yeah, I was just thinking about this the other day. I'm not even sure this should be a parameter in `extract_features`.
