### ISSUE TITLE
Update for TensorFlow 1.14+

### ISSUE THREAD

**Issue by jon-harmon-macmillan** [jonathanbratt/RBERT#5]
We had to specify TF 1.11.0 to get the tests in test_modeling.R and test_run_classifier.R to work. What is it about those tests that's 1.11-specific?

**Comment by jonathanbratt** [comment]
Something about TF v 1.14 & R v 3.6 seems to result in segfaults for some reason.
I don't know if this is related to any of the other tensorflow segfault reports that a google search turns up. Will try to narrow down further.

**Comment by jonathanbratt** [comment]
It's possible this issue is also related to python version.
I trigger a bunch of warnings (but no segfaults) when running extract_features with

- TF v. 1.14
- R v. 3.5.1
- python 2.7.5

Warnings are something like:

> WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fbcc41bbb90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fbcc41bbb90>>: AssertionError: Bad argument number for Name: 3, expecting 4

These warnings do not appear using an earlier version of TensorFlow.

**Comment by jonathanbratt** [comment]
A very similar warning is reported in this issue:
https://github.com/tensorflow/tensorflow/issues/32383

**Comment by mihaimaruseac** [comment]
Please make sure to install `gast==0.2.2` as they released a backwards incompatible change.

TF handles this for 1.15 and 2.0 and later, but we cannot fix the earlier versions

**Comment by jonathanbratt** [comment]
Aha, thanks!

**Comment by jonthegeek** [comment]
I think we should focus on #28, and then go all-TF2 for the package (and thus close this issue). Thoughts?

**Comment by jonathanbratt** [comment]
yup, I agree. (I guess I kind of noted that in #28, but didn't also comment here.)
