### ISSUE TITLE
Speed Up `extract_features`

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/RBERT#50]
I think there are still a few tricks we could do to speed this up. Since this is the workhorse of the package, let's do everything we can to get there. Might need to look into base and/or data.table to replace some of the tidyr stuff I have in there.

I also want to look one more time at whether I'm "thinking" about the raw output from tensorflow correctly. In theory it should be sending back a `max_seq_length` x `embeddings` matrix for each layer for each example. That shouldn't be TOO hard to tibble-ize. If the slowness is inside the actual BERT work, ok, we can't do anything about it... but I think a lot of it is still in this function.

**Comment by jonthegeek** [comment]
Line 609, it might help to pre-declare the size of the unique_id_to_feature list.

Line 634: What does the "yield_single_examples" argument do?

**Comment by jonathanbratt** [comment]
re: pre-declaring size: sure, that would be an easy change.

re: `yield_single_examples`: 
Here's the TF documentation on that parameter:

> yield_single_examples: If False, yields the whole batch as returned by the model_fn instead of decomposing the batch into individual elements. This is useful if model_fn returns some tensors whose first dimension is not equal to the batch size.

So... *maybe* there's a speed-up to be had there? `TRUE` is the default, so it's listed explicitly just as a reminder. Might be worth testing sometime.

**Comment by jonthegeek** [comment]
1. I confirmed that `yield_single_examples = FALSE` would return everything at once, may need to look into this in the future, but...
2. Almost all of the time is in the actual BERT part of this, not in the parsing. 

Digging a little more...

**Comment by jonthegeek** [comment]
Almost all of the time is spent in tf$contrib, which doesn't exist in TF2.0, so we should probably ignore this until we do the TF2.0 refactor.

**Comment by jonthegeek** [comment]
This version of this ticket is meaningless with TF2.
