### ISSUE TITLE
Move Tokenizer to Separate Package

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/RBERT#55]
As an RBERT dev, I'd like the wordpiece tokenizer to be in its own optimizable package, so that I don't have to think about it.

**Comment by jonthegeek** [comment]
What we need is (mostly) in `sentencepiece::wordpiece_encode`. I plan to pull that out, but for now we should use that.

**Comment by jonathanbratt** [comment]
In the tf2 branch, this is done, using our wordpiece package now on CRAN.
