### ISSUE TITLE
include zeroth-level embeddings in extract_features

### ISSUE THREAD

**Issue by jonathanbratt** [jonathanbratt/RBERT#6]
For completeness, would be good to return the bare token embeddings before any transformer layers along with the layer outputs.

**Comment by leungi** [comment]
If I understand this post correctly, in most BERT-related articles, when 12 layers are mentioned for the _uncased_ model, this corresponds to `layer_output_1` to `layer_output_12` in output from `RBERT::extract_features()`, ya?

**Comment by jonathanbratt** [comment]
That is correct. When you see `layer_output_0` in RBERT output, that corresponds to the vectors *input* to the first transformer layer.
