### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by jyl19** [jonathanbratt/RBERT#66]
Hi RBERT team, 

Thank you all for putting this together. I'm working on transitioning to using BERT as my preferred set of embeddings, but since I program almost exclusively in R, I figured I was out of luck. Everything in this package seems tremendous, and I thank you for putting in such hard work. 

As it stands, I'm having issues installing the package on my computer. When I run:

devtools::install_github(
  "jonathanbratt/RBERT", 
  build_vignettes = TRUE
)

I'm asked to update several packages. Fine, not a big deal. 

But every time we get past that, I receive this error:

"Error: Failed to install 'RBERT' from GitHub:
  'local_makevars' is not an exported object from 'namespace:withr'"

I've updated withr to try and fix things (to no avail). This reminded me of an issue I ran into with using rstan before (see here for a discussion: https://github.com/stan-dev/rstan/pull/857) that I was ultimately able to workaround. 

I'm assuming my problems come from the fact that I'm stuck using a Windows computer. Here's my R version information if that helps: 

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out     

Is there anything I can do to work around this? Since I'm trying to use this for work, I cannot switch OS.

**Comment by jonathanbratt** [comment]
Thanks for the note!
I don't use a Windows machine, but @jonthegeek does, so maybe he can give you some advice?

Just a heads up: we're working on a package that implements BERT using the "torch" R package. This should be a lot easier to install and maintain than the TensorFlow implementation. We hope to make this available before too long.

**Comment by jyl19** [comment]
That's great to hear. Yeah, I realized after I submitted this that this could be a version control issue with TensorFlow or something. But I think that the issue is something about how windows works with compilation--hence why it seems to be similar to the Stan problem I linked to. 

Hopefully switching to Torch will get around that. Thanks again for the reply.

**Comment by jonthegeek** [comment]
For what it's worth, we don't do anything with withr and don't have any compiled code, so that particular error comes from something else. Do you have something about withr in your .Rprofile, maybe? I don't think this is a Windows thing, per se, but it COULD be from something you had to do to get stan to install.

**Comment by jyl19** [comment]
Oh yeah, that last remark I think is probably right. I had to alter my .Rprofile to get Stan's compilers to work. I suspect doing that messed with something here. Well, that's good to know. I'll try this from a clean install later and see if that works.  I'll also mess around with withr and see if uninstalling that at least lets me install the package.

Thanks!

**Comment by jyl19** [comment]
So removing withr for installation was sufficient to install RBERT. Thanks again!
