### ISSUE TITLE
Not getting to download the bert_base_uncased

### ISSUE THREAD

**Issue by gydrqjones** [jonathanbratt/RBERT#69]
On running the package for the first time and am getting the below error message - please can you offer some guidance -thanks

'rDownloading' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jonathanbratt** [comment]
Thanks for the note!
Without digging into it further, my guess is it has something to do with package versions or the Python/TensorFlow installation. In either case, I suggest taking a look at our newer packages, [torchtransformers](https://github.com/macmillancontentscience/torchtransformers) and [tidybert](https://github.com/macmillancontentscience/tidybert). These provide the same functionality as RBERT (and more), but are built on the R torch package, so no Python installation is required.

**Comment by gydrqjones** [comment]
Gratitude! I was able to successfully install them. by chance where can get the documentation on how to use the two as I am new to this - thanks.

**Comment by jonathanbratt** [comment]
Great! I suggest you start with the "basic usage" vignette in the tidybert package. If you run into any trouble, please create an issue in the corresponding package.

We haven't got around to finding a new home for the visualization routines, so the [RBERTviz](https://github.com/jonathanbratt/RBERTviz) package may still be useful.
